---
# tasks file for ansible-role-dehydrated
- name: "Install packages"
  apt:
    name: "{{ item }}"
  with_items: "{{ dehydrated_packages }}"
- name: "Create /etc/dehydrated/conf.d/local.sh"
  template:
    src: local.sh.j2
    dest: /etc/dehydrated/conf.d/local.sh
- name: "Create /etc/dehydrated/domains.txt"
  template:
    src: domains.txt.j2
    dest: /etc/dehydrated/domains.txt

- name: "Install local-dehydrated timer"
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify: Enable a timer for local-dehydrated
  with_items:
  - "local-dehydrated.service"
  - "local-dehydrated.timer"
